name: Run Selenium Scraper

on:
  schedule:
    - cron: "0 6,18 * * *"  # Uruchamia się codziennie o 6:00 i 18:00 UTC
  workflow_dispatch:  # Pozwala uruchomić ręcznie z poziomu GitHub Actions

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzenie repozytorium
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl

      - name: Pobranie i konfiguracja przeglądarki Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-chromedriver
          echo "CHROME_BIN=$(which chromium-browser)" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=$(which chromedriver)" >> $GITHUB_ENV

      - name: Uruchomienie skryptu
        run: python NL_schedule.py

      - name: Commit i push nowego pliku Excel
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase origin main 
          git add Rotterdam_schedule.xlsx
          git commit -m "Automatyczna aktualizacja danych Rotterdam_schedule.xlsx" || echo "Brak zmian do zapisania"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
