name: Run Selenium Scraper

on:
  schedule:
    - cron: "0 6,18 * * *"  # Uruchamia się codziennie o 6:00 i 18:00 UTC
  workflow_dispatch:  # Pozwala uruchomić ręcznie z poziomu GitHub Actions

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzenie repozytorium
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl

      - name: Pobranie i konfiguracja przeglądarki Chrome
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          
          # Pobranie i instalacja Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          
          # Pobranie i instalacja ChromeDriver
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -N https://chromedriver.storage.googleapis.com/${CHROME_VERSION}.0.0/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Ustawienie zmiennych środowiskowych
          echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/local/bin/chromedriver" >> $GITHUB_ENV

      - name: Uruchomienie skryptu
        run: python NL_schedule.py

      - name: Commit i push nowego pliku Excel
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase origin main 
          git add Rotterdam_schedule.xlsx
          git commit -m "Automatyczna aktualizacja danych Rotterdam_schedule.xlsx" || echo "Brak zmian do zapisania"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Karolik-Aleksandra-one/schedule.git main
