name: Run Selenium Scraper

on:
  schedule:
    - cron: "0 6,18 * * *"  # Uruchamia się codziennie o 6:00 i 18:00 UTC
  workflow_dispatch:  # Pozwala uruchomić ręcznie z poziomu GitHub Actions

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzenie repozytorium
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl

      - name: Pobranie i konfiguracja przeglądarki Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver

          # Sprawdzenie wersji Chromium i WebDrivera
          chromium-browser --version
          chromedriver --version

          # Ustawienie zmiennych środowiskowych
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV
                   

      - name: Uruchomienie skryptu
        run: python NL_schedule.py

      - name: Commit i push nowego pliku Excel
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase origin main 
          git add Rotterdam_schedule.xlsx
          git commit -m "Automatyczna aktualizacja danych Rotterdam_schedule.xlsx" || echo "Brak zmian do zapisania"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Karolik-Aleksandra-one/schedule.git main
